name: Deploy React.js application

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u shakir737 -p Anilla621#
      - name: Build docker image
        run: docker build -t shakir737/ecomerse-frontend .
      - name: Publish image to docker hub
        run: docker push  shakir737/ecomerse-frontend:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull shakir737/ecomerse-frontend:latest
      - name: Delete old container
        run: docker rm -f reactjs-app-container
      - name: Run docker container
        run: docker run -d -p 3000:80 --name reactjs-app-container  shakir737/ecomerse-frontend
